export * from './Perfil'
export * from './Estudios'
export * from './Experiencia'
export * from './Habilidades'
export * from './Experiencia'
export * from './Portafolio'
export * from './Contacto'
export * from '../../routes/Footer'