export * from './Home/Home'
export * from './Profile/Profile'
export * from './Skills/Skills'
export * from './Formation/Formation'
export * from './Experience/Experience'
export * from './Portfolio/Portfolio'
export * from './Contact/Contact'
